SKILLS = [

    "angular",
    "aws",
    "azure",
    "c++",
    "css",
    "data analysis",
    "data visualization",
    "deep learning",
    "django",
    "docker",
    "excel",
    "express",
    "flask",
    "html",
    "java",
    "javascript",
    "kubernetes",
    "machine learning",
    "mongodb",
    "mysql",
    "nlp",
    "node",
    "numpy",
    "panda",
    "pandas",
    "postgresql",
    "power bi",
    "python",
    "pytorch",
    "react",
    "ruby",
    "scikit-learn",
    "sql",
    "statistics",
    "streamlit",
    "tableau",
    "tensorflow",

]